version: "3.7"
services:
  flask-ner:
    build: ./
    container_name: demos_backend_ner
    environment:
      - FLASK_ENV=development
      - SAMPLES_DIR=./samples
    ports:
      - 8003:5000
    volumes:
      - ./:/app
      - ./tls:/tls
    command: uwsgi  --http 0.0.0.0:5000 --callable app  --wsgi-file app/ner.py
    restart: always

  # flask-neuro-ner:
  #   build: ./backend/neuro-ner
  #   container_name: demos_backend_neuro_ner
  #   environment:
  #     - FLASK_ENV=development
  #     - SAMPLES_DIR=./samples
  #   ports:
  #     - 8004:5000
  #   volumes:
  #     - ./backend/neuro-ner:/app
  #     - ./NER-Models:/root/.rbbt/share/models/TeMU/NeuroNER/
  #     - ./tls:/tls
  #   command: flask run --host 0.0.0.0 --cert="/tls/certs/textmining.bsc.es.pem" --key="/tls/keys/textmining.bsc.es.decrypt.key"

  # flask-spacy-ner:
  #   build: ./backend/spacy_server
  #   container_name: demos_backend_spacy
  #   environment:
  #     - FLASK_ENV=development
  #     - SAMPLES_DIR=./samples
  #   ports:
  #     - 8005:5000
  #   volumes:
  #     - ./backend/spacy_server:/app
  #     - ./NER-Models:/spacy_models
  #     - ./tls:/tls
  #   command: flask run --host 0.0.0.0 --cert="/tls/certs/textmining.bsc.es.pem" --key="/tls/keys/textmining.bsc.es.decrypt.key"
  #   restart: always
